title: Arttu's site
author: ArttuPee
email: arttu.pyykonen105@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is all about my journey to becomming a developer.
  I will share my progress and help others do it with me. 
  Together we can do it!
theme: minima
# social links
twitter_username: ArttuPyykonen # DO NOT include the @ character, or else the build will fail!
github_username:  ArttuPee # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
